name: Deploy Package
permissions:
  id-token: write # Required for OIDC
  contents: write # Required to push to gh-pages
on:
  push:
    branches: [release]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Select Node Version
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Install Deps
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test

      - name: Generate Coverage
        run: pnpm cc

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Release Package
        run: pnpm build-package

      - run: 'npm install -g npm@^11.0.0'

      - run: 'npm --version'

      - name: Publish To NPM
        run: npm publish ./package --tag beta

      - name: Install Doc Dependencies
        run: cd docs-site && pnpm install

      - name: Generate Documentation
        run: rm -rf ./docs && pnpm generate-docs

      - name: Deploy Documentation
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          cname: iso-fns.org
